== f ==
fun f() {
    var foo = 1
    try {
        foo = 2
        throw RuntimeException()
    } catch (e: Throwable) {
        println(foo)
    }
}
---------------------
                                                                                                 <v4>: *                NEW: magic[CATCH_FROM_TRY](try { foo = 2 throw RuntimeException() } catch (e: Throwable) { println(foo) }) -> <v4>
                                                                                                 <v5>: {<: Throwable}   NEW: magic[FAKE_INITIALIZER](e: Throwable) -> <v5>
                                                                                                 <v9>: *                NEW: magic[OUT_OF_CATCH](try { foo = 2 throw RuntimeException() } catch (e: Throwable) { println(foo) }) -> <v9>
1                                                                                                <v0>: Int              NEW: r(1) -> <v0>
2                                                                                                <v1>: Int              NEW: r(2) -> <v1>
RuntimeException()                                                                               <v2>: {<: Throwable}   NEW: call(RuntimeException(), <init>) -> <v2>
throw RuntimeException()                                                                         !<v3>: *
{ foo = 2 throw RuntimeException() }                                                             !<v3>: *               COPY
println                                                                                          !<v7>: *
foo                                                                                              <v6>: *                NEW: r(foo) -> <v6>
println(foo)                                                                                     <v8>: *                NEW: magic[UNRESOLVED_CALL](println(foo)|<v6>, !<v7>) -> <v8>
{ println(foo) }                                                                                 <v8>: *                COPY
try { foo = 2 throw RuntimeException() } catch (e: Throwable) { println(foo) }                   <v10>: *               NEW: merge(try { foo = 2 throw RuntimeException() } catch (e: Throwable) { println(foo) }|!<v3>, <v8>) -> <v10>
{ var foo = 1 try { foo = 2 throw RuntimeException() } catch (e: Throwable) { println(foo) } }   <v10>: *               COPY
=====================
